#!/bin/sh -

JAVA="java"

if [ -x "$JAVA_HOME/bin/java" ] ; then
    JAVA="$JAVA_HOME/bin/java"
fi

$JAVA -classpath ./lib/alice.jar:./externalLib/AppleJavaExtensions.jar:./externalLib/customizer.jar:./externalLib/getopt-1.0.7.jar:./externalLib/gluegen-rt.jar:./externalLib/j3dcore.jar:./externalLib/j3dutils.jar:./externalLib/javazoom.jar:./externalLib/jl1.0.jar:./externalLib/jmf.jar:./externalLib/jogl.jar:./externalLib/jython.jar:./externalLib/mediaplayer.jar:./externalLib/mp3plugin.jar:./externalLib/multiplayer.jar:./externalLib/resolver.jar:./externalLib/rt.jar:./externalLib/sound.jar:./externalLib/vecmath.jar:./externalLib/xercesImpl.jar:./externalLib/xercesSamples.jar:./externalLib/xml-apis.jar:./externalLib/xmlParserAPIs.jar -Dpython.home=./jython-2.1 -Dpython.path=./jython-2.1/Lib/alice -Djava.library.path=./lib/linux-i586 -Xms64m -Xmx1024m -Dfile.encoding=ISO-8859-1 edu.cmu.cs.stage3.alice.authoringtool.JAlice
